version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
